/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NowRouteImport } from './routes/now'
import { Route as PicturesRouteImport } from './routes/pictures'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MusingsIndexRouteImport } from './routes/musings.index'
import { Route as MusingsSlugRouteImport } from './routes/musings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PicturesRoute = PicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MusingsIndexRoute = MusingsIndexRouteImport.update({
  id: '/musings/',
  path: '/musings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusingsSlugRoute = MusingsSlugRouteImport.update({
  id: '/musings/$slug',
  path: '/musings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/pictures': typeof PicturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/musings/$slug': typeof MusingsSlugRoute
  '/musings/': typeof MusingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/pictures': typeof PicturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/musings/$slug': typeof MusingsSlugRoute
  '/musings': typeof MusingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/pictures': typeof PicturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/musings/$slug': typeof MusingsSlugRoute
  '/musings/': typeof MusingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/now'
    | '/pictures'
    | '/sitemap.xml'
    | '/musings/$slug'
    | '/musings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/now'
    | '/pictures'
    | '/sitemap.xml'
    | '/musings/$slug'
    | '/musings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/now'
    | '/pictures'
    | '/sitemap.xml'
    | '/musings/$slug'
    | '/musings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NowRoute: typeof NowRoute
  PicturesRoute: typeof PicturesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MusingsSlugRoute: typeof MusingsSlugRoute
  MusingsIndexRoute: typeof MusingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pictures': {
      id: '/pictures'
      path: '/pictures'
      fullPath: '/pictures'
      preLoaderRoute: typeof PicturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musings/': {
      id: '/musings/'
      path: '/musings'
      fullPath: '/musings/'
      preLoaderRoute: typeof MusingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musings/$slug': {
      id: '/musings/$slug'
      path: '/musings/$slug'
      fullPath: '/musings/$slug'
      preLoaderRoute: typeof MusingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NowRoute: NowRoute,
  PicturesRoute: PicturesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MusingsSlugRoute: MusingsSlugRoute,
  MusingsIndexRoute: MusingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
